/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardSolutionsRouteImport } from './routes/dashboard.solutions'
import { Route as DashboardSearchRouteImport } from './routes/dashboard.search'
import { Route as DashboardApikeysRouteImport } from './routes/dashboard.apikeys'
import { Route as DashboardSolutionsSolutionIdRouteImport } from './routes/dashboard.solutions.$solutionId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSolutionsRoute = DashboardSolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSearchRoute = DashboardSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApikeysRoute = DashboardApikeysRouteImport.update({
  id: '/apikeys',
  path: '/apikeys',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSolutionsSolutionIdRoute =
  DashboardSolutionsSolutionIdRouteImport.update({
    id: '/$solutionId',
    path: '/$solutionId',
    getParentRoute: () => DashboardSolutionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/dashboard/apikeys': typeof DashboardApikeysRoute
  '/dashboard/search': typeof DashboardSearchRoute
  '/dashboard/solutions': typeof DashboardSolutionsRouteWithChildren
  '/dashboard/solutions/$solutionId': typeof DashboardSolutionsSolutionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/dashboard/apikeys': typeof DashboardApikeysRoute
  '/dashboard/search': typeof DashboardSearchRoute
  '/dashboard/solutions': typeof DashboardSolutionsRouteWithChildren
  '/dashboard/solutions/$solutionId': typeof DashboardSolutionsSolutionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/dashboard/apikeys': typeof DashboardApikeysRoute
  '/dashboard/search': typeof DashboardSearchRoute
  '/dashboard/solutions': typeof DashboardSolutionsRouteWithChildren
  '/dashboard/solutions/$solutionId': typeof DashboardSolutionsSolutionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/demo'
    | '/learn'
    | '/login'
    | '/dashboard/apikeys'
    | '/dashboard/search'
    | '/dashboard/solutions'
    | '/dashboard/solutions/$solutionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/demo'
    | '/learn'
    | '/login'
    | '/dashboard/apikeys'
    | '/dashboard/search'
    | '/dashboard/solutions'
    | '/dashboard/solutions/$solutionId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/demo'
    | '/learn'
    | '/login'
    | '/dashboard/apikeys'
    | '/dashboard/search'
    | '/dashboard/solutions'
    | '/dashboard/solutions/$solutionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DemoRoute: typeof DemoRoute
  LearnRoute: typeof LearnRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/solutions': {
      id: '/dashboard/solutions'
      path: '/solutions'
      fullPath: '/dashboard/solutions'
      preLoaderRoute: typeof DashboardSolutionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/search': {
      id: '/dashboard/search'
      path: '/search'
      fullPath: '/dashboard/search'
      preLoaderRoute: typeof DashboardSearchRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/apikeys': {
      id: '/dashboard/apikeys'
      path: '/apikeys'
      fullPath: '/dashboard/apikeys'
      preLoaderRoute: typeof DashboardApikeysRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/solutions/$solutionId': {
      id: '/dashboard/solutions/$solutionId'
      path: '/$solutionId'
      fullPath: '/dashboard/solutions/$solutionId'
      preLoaderRoute: typeof DashboardSolutionsSolutionIdRouteImport
      parentRoute: typeof DashboardSolutionsRoute
    }
  }
}

interface DashboardSolutionsRouteChildren {
  DashboardSolutionsSolutionIdRoute: typeof DashboardSolutionsSolutionIdRoute
}

const DashboardSolutionsRouteChildren: DashboardSolutionsRouteChildren = {
  DashboardSolutionsSolutionIdRoute: DashboardSolutionsSolutionIdRoute,
}

const DashboardSolutionsRouteWithChildren =
  DashboardSolutionsRoute._addFileChildren(DashboardSolutionsRouteChildren)

interface DashboardRouteChildren {
  DashboardApikeysRoute: typeof DashboardApikeysRoute
  DashboardSearchRoute: typeof DashboardSearchRoute
  DashboardSolutionsRoute: typeof DashboardSolutionsRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardApikeysRoute: DashboardApikeysRoute,
  DashboardSearchRoute: DashboardSearchRoute,
  DashboardSolutionsRoute: DashboardSolutionsRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DemoRoute: DemoRoute,
  LearnRoute: LearnRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
